### ISSUE TITLE
No Bot Config

### ISSUE THREAD

**Issue by JustLikeNone** [winglessraven/AMP-Discord-Bot#103]
**Describe the bug**
No bot control in Configuration screen after installing.. same as #97 

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'instance config'
4. does not see discord bot

**Expected behaviour**
Discord bot config to be there

**Screenshots**
![image](https://github.com/winglessraven/AMP-Discord-Bot/assets/62360322/14f4e4e9-d149-480a-b66e-4f2bbc6938fb)

**AMP Instance Info (please complete the following information):**
 - OS: win 11
 - AMP v2.5.0.14, built 14/06/2024 03:45

**Comment by JustLikeNone** [comment]
[19:21:22] [Program Info/1]       : Starting AMP version 2.5.0.14 (Callisto), built 14/06/2024 03:45
[19:21:22] [Program Info/1]       : Stream: Mainline / Release - built by CUBECODERS/buildbot on CCL-DEV
[19:21:22] [Core Info/1]          : Loading configuration from provisionargs.kvp...
[19:21:23] [Core Warning/1]       : Current time zone is set to Arab Standard Time - It is recommended you switch to UTC+0 to avoid time-zone related issues
[19:21:23] [Program Info/1]       : OS: Windows / x86_64
[19:21:23] [Program Info/1]       : CPU: 13th Gen Intel(R) Core(TM) i5-13600K (14C/20T)
[19:21:23] [Program Info/1]       : RAM: 32509MB
[19:21:23] [Program Info/1]       : AMP Instance ID: 0a6c644d-3afb-40c7-abfc-6d382b9d280e
[19:21:23] [Loader Info/1]        : Loaded MinecraftModule version 1.0.0.3 by CubeCoders Limited
[19:21:23] [Core Info/1]          : Metrics publishing is enabled at udp://localhost:12820.
[19:21:23] [Loader Info/1]        : Loaded FileManagerPlugin by CubeCoders Limited
[19:21:23] [Loader Info/1]        : Loaded EmailSenderPlugin by CubeCoders Limited
[19:21:23] [Loader Info/1]        : Loaded WebRequestPlugin by CubeCoders Limited
[19:21:24] [Loader Info/1]        : Loaded LocalFileBackupPlugin by CubeCoders Limited
[19:21:24] [Loader Info/1]        : Loaded CommonCorePlugin by CubeCoders Limited
[19:21:24] [Core Error/1]         : CryptographicException
[19:21:24] [Core Error/1]         : [0] (CryptographicException) : Cannot find the requested object.

[19:21:24] [Core Error/1]         :    at Security.Cryptography.CryptographicException.ThrowCryptographicException(Int32 hr)
   at Security.Cryptography.X509Certificates.X509Utils._QueryCertFileType(String fileName)
   at Security.Cryptography.X509Certificates.X509Certificate.LoadCertificateFromFile(String fileName, Object password, X509KeyStorageFlags keyStorageFlags)
   at GSMyAdmin.SignatureVerification.Verify_Windows(String Filename)
[19:21:24] [Loader Error/1]       : Unable to load plugin DiscordBotPlugin: Could not load file or assembly 'DiscordBotPlugin' or one of its dependencies. Failure during Cryptographic operation. (Exception from HRESULT: 0x80131430)
[19:21:24] [Loader Error/1]       : Could not load plugin DiscordBotPlugin
[19:21:24] [Core Info/1]          : Performing activation, please wait...
[19:21:25] [Core Info/1]          : Activated successfully.
[19:21:25] [Core Info/1]          : Licence Present: AMP Standard Edition
[19:21:25] [Program Info/1]       : -configonly specified or activation performed. Saving settings and shutting down. This is perfectly normal.

**Comment by winglessraven** [comment]
The log suggests you haven't applied the AMP developer license to the instance

**Comment by JustLikeNone** [comment]
> The log suggests you haven't applied the AMP developer license to the instance

oh i am sorry i though the normal license is the same as dev but it was diffrent
thanks it worked now :)
