### ISSUE TITLE
Bug when installing plugin on a new instance 

### ISSUE THREAD

**Issue by Jonny-Havoc** [winglessraven/AMP-Discord-Bot#104]
**Describe the bug**
The bot configuration options do not show up with a new Valheim instance in AMP.  An option named Discord Bot:Smart_toy will show but it has no parameters. No errors showing in log.  

**To Reproduce**
Steps to reproduce the behaviour:
1. Install DiscordBotPlugin.dll to new Valheim instance
2. Edit AMPConfig.conf to reference the plugin 
3. Reactivate instance with developer licence key 
4. Start instance, Discord Bot configuration options are not present in the UI 

**Expected behaviour**
 Discord Bot configuration options to be present and configurable in the UI 

**Screenshots**
![discord bug bot](https://github.com/winglessraven/AMP-Discord-Bot/assets/116952614/fc3d8296-0d4a-4148-b0a8-05176a733298)

**AMP Instance Info (please complete the following information):**
 - OS: Windows 11 Professional 
 - AMP Release "Callisto" v2.5.0.14, built 14/06/2024 03:45

**Additional context**
I have used this bot on all my other instances including a Valheim instance in the past and have not had this issue before 

[09:57:59] [Program Info/1]       : Starting AMP version 2.5.0.14 (Callisto), built 14/06/2024 03:45
[09:57:59] [Program Info/1]       : Stream: Mainline / Release - built by CUBECODERS/buildbot on CCL-DEV
[09:57:59] [Core Warning/1]       : Current time zone is set to New Zealand Standard Time - It is recommended you switch to UTC+0 to avoid time-zone related issues
[09:57:59] [Program Info/1]       : OS: Windows / x86_64
[09:57:59] [Program Info/1]       : CPU: Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (4C/8T)
[09:57:59] [Program Info/1]       : RAM: 16256MB
[09:57:59] [Program Info/1]       : AMP Instance ID: cc741ab0-793b-45b6-86a9-125e70bf17b8
[09:58:00] [Loader Info/1]        : Loaded GenericModule version 1.0.0.0 by CubeCoders Limited
[09:58:00] [Core Info/1]          : Metrics publishing is enabled at udp://localhost:12820.
[09:58:00] [Loader Info/1]        : Loaded FileManagerPlugin by CubeCoders Limited
[09:58:00] [Loader Info/1]        : Loaded EmailSenderPlugin by CubeCoders Limited
[09:58:00] [Loader Info/1]        : Loaded WebRequestPlugin by CubeCoders Limited
[09:58:00] [Loader Info/1]        : Loaded LocalFileBackupPlugin by CubeCoders Limited
[09:58:00] [Loader Info/1]        : Loaded CommonCorePlugin by CubeCoders Limited
[09:58:00] [Core Error/1]         : CryptographicException
[09:58:00] [Core Error/1]         : [0] (CryptographicException) : Cannot find the requested object.

[09:58:00] [Core Error/1]         :    at Security.Cryptography.CryptographicException.ThrowCryptographicException(Int32 hr)
   at Security.Cryptography.X509Certificates.X509Utils._QueryCertFileType(String fileName)
   at Security.Cryptography.X509Certificates.X509Certificate.LoadCertificateFromFile(String fileName, Object password, X509KeyStorageFlags keyStorageFlags)
   at GSMyAdmin.SignatureVerification.Verify_Windows(String Filename)
[09:58:01] [Loader Info/1]        : Loaded DiscordBotPlugin by winglessraven
[09:58:01] [Loader Info/1]        : GenericModule requests dependency steamcmdplugin...
[09:58:01] [Loader Info/1]        : Loaded steamcmdplugin by CubeCoders Limited
[09:58:01] [Loader Info/1]        : GenericModule requests dependency RCONPlugin...
[09:58:01] [Loader Info/1]        : Loaded RCONPlugin by CubeCoders Limited
[09:58:01] [Core Info/1]          : Licence Present: AMP Professional Edition
[09:58:01] [Core Info/1]          : Licence Present: AMP Developer Edition
[09:58:01] [FileManager Notice/1] : Using keypair with fingerprint 64YmL6rvrJgRB30qS6Zhaz+tx67FGX1f0mak2rNRyJU=
[09:58:01] [FileManager Info/1]   : SFTP Server started on 192.168.10.227:4508
[09:58:01] [Webserver Info/1]     : Websockets are enabled.
[09:58:01] [Webserver Info/1]     : Webserver started on http://192.168.10.227:4503
[09:58:01] [Webserver Info/13]    : RouterTimer@10Hz with 2 jobs started
[09:58:01] [Core Info/1]          : Checking for AMP updates...
[09:58:03] [Core Info/10]         : AMP is up to date.
[09:58:12] [Core Activity/10]     : Authentication attempt for user admin from 192.168.10.227
[09:58:13] [Core Activity/9]      : Authentication success

**Comment by winglessraven** [comment]
Something strange going on - you don't have the icons in the options. 
![image](https://github.com/winglessraven/AMP-Discord-Bot/assets/4540397/d689de00-21fa-4b70-948d-e27adbb935b8)

Do you have tabs if you go into any of the other items in the menu? 
![image](https://github.com/winglessraven/AMP-Discord-Bot/assets/4540397/af1c84c7-aac8-430d-8b6b-c7673d1d7ce0)

The latest version of the bot has the icon (this is where smart_toy comes from) and is split into tabs. If your tabs are not working then that would explain why no options are showing up.

**Comment by Jonny-Havoc** [comment]
That is strange, my AMP does not have those icons, nor does it have tabs

**Comment by Jonny-Havoc** [comment]
I think I understand the issue, my ADS is on v2.4.8, that is probably why I cannot see the tabs. 

I will test this tomorrow, thank you for your quick response and assistance :)
