### ISSUE TITLE
Discord Bot not starting

### ISSUE THREAD

**Issue by Projoreo** [winglessraven/AMP-Discord-Bot#108]
**Describe the bug**

CryptographicException
[0] (CryptographicException) : Cannot find the requested object.
at Security.Cryptography.CryptographicException.ThrowCryptographicException(Int32 hr) at Security.Cryptography.X509Certificates.X509Utils._QueryCertFileType(String fileName) at Security.Cryptography.X509Certificates.X509Certificate.LoadCertificateFromFile(String fileName, Object password, X509KeyStorageFlags keyStorageFlags) at GSMyAdmin.SignatureVerification.Verify_Windows(String Filename)
Unable to load plugin DiscordBotPlugin: Could not load file or assembly 'DiscordBotPlugin' or one of its dependencies. Failure during Cryptographic operation. (Exception from HRESULT: 0x80131430)

**To Reproduce**
Stopping and restarting doesnt help

**AMP Instance Info (please complete the following information):**
 - OS: Windows
 - AMP Build 2.5.1.6

**Comment by winglessraven** [comment]
Can you attach the whole log file? The crypto error is normal on Windows but the plugin still usually loads.

Need the full log for some more context.

**Comment by Projoreo** [comment]
Im not exactly sure if this is it

lmk if there is a different one you need

08:15:44
Assembly Newtonsoft.Json was loaded for Core via fallback handler, check plugin dependencies.
Loaded ADSModule version 1.0.0.0 by CubeCoders Limited
Loaded FileManagerPlugin by CubeCoders Limited
Loaded EmailSenderPlugin by CubeCoders Limited
Loaded WebRequestPlugin by CubeCoders Limited
Loaded CommonCorePlugin by CubeCoders Limited
CryptographicException
[0] (CryptographicException) : Cannot find the requested object.
at Security.Cryptography.CryptographicException.ThrowCryptographicException(Int32 hr) at Security.Cryptography.X509Certificates.X509Utils._QueryCertFileType(String fileName) at Security.Cryptography.X509Certificates.X509Certificate.LoadCertificateFromFile(String fileName, Object password, X509KeyStorageFlags keyStorageFlags) at GSMyAdmin.SignatureVerification.Verify_Windows(String Filename)
Unable to load plugin DiscordBotPlugin: Could not load file or assembly 'DiscordBotPlugin' or one of its dependencies. Failure during Cryptographic operation. (Exception from HRESULT: 0x80131430)
Could not load plugin DiscordBotPlugin
ADSModule requests dependency InstanceManagerPlugin...
08:15:45
Loaded InstanceManagerPlugin by CubeCoders Limited
ADSModule requests dependency SystemUserManagerPlugin...
Loaded SystemUserManagerPlugin by CubeCoders Limited
Licence Present: AMP Standard Edition - Lifetime Licence
Loaded steamcmdplugin by CubeCoders Limited
Metrics server started OK on port 12820
ADS startup complete in 240ms
Updating remote source CubeCoders/AMPTemplates
Using keypair with fingerprint wmc6UF9RZqyHNOMKU9SIHSoGtPdf9OJoCZBNxZzVCDg=
08:15:46
SFTP Server started on 0.0.0.0:2223
Websockets are enabled.
08:15:47
Webserver started on http://0.0.0.0:8080
RouterTimer@10Hz with 2 jobs started
Checking for AMP updates...
Startup mode is UpdateAndStart.
AMP is up to date.
