### ISSUE TITLE
No port information available.

### ISSUE THREAD

**Issue by Bovive** [winglessraven/AMP-Discord-Bot#120]
**Describe the bug**
After applying the bot to an instance, the Network Port Status displays as "No port information available". It still functions just fine and the ports are open and working, it appears to just be a display issue in the instance. It does not occur to instances that I have not applied the bot to. I did not apply the bot to my Main ADS instance.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a new instance.
2. Apply bot to instance using script.
3. The Network Port Status now displays as "No port information available". 

**Expected behaviour**
I have used this before and this did not happen. I expect it to start back up showing the ports.

**Screenshots**
Here is what it looks like after applying the bot:
<img width="760" alt="Error" src="https://github.com/user-attachments/assets/91af30c4-60f2-49c6-8773-b76bb52320e4">

**AMP Instance Info (please complete the following information):**
 - OS: Unraid/Docker
 - AMP Build: v2.606

**Additional context**
There is an error in the logs, I am unsure if it is related:

```
[17:08:37] [System Error/10]      : Missing plugin/assembly: MaxMind.Db (/home/amp/.ampdata/instances/Impostor-AmongUsServer01/Plugins/MaxMind.Db/MaxMind.Db.dll) for DiscordBotPlugin
[17:08:37] [SignatureVerification Error/1] : ArgumentNullException
[17:08:37] [SignatureVerification Error/1] : [0] (ArgumentNullException) : Value cannot be null. (Parameter 'rawData')
[17:08:37] [SignatureVerification Error/1] :    at ArgumentNullException.Throw(String paramName)
   at Security.Cryptography.X509Certificates.X509Certificate2Collection.Import(Byte[] rawData)
   at GSMyAdmin.SignatureVerification.GetCertFromFile(String Filename)
   at GSMyAdmin.SignatureVerification.Verify_Certificate(String Filename)
[17:08:37] [Loader Info/1]        : Loaded DiscordBotPlugin by winglessraven
```

**Comment by Bovive** [comment]
Just an update. This appears to occur when the developer key is applied to the instance. I am unsure if this is isolated to this plugin or for developer keys as a whole.

**Comment by winglessraven** [comment]
Thanks for the additional info, indeed it does seem to be unrelated to the plugin.

The error about MaxMind.db can be ignored - I've flagged this with CubeCoders.

I'm wondering if this is more something to do with Unraid setup.

This is a new instance created yesterday with my plugin enabled...

![image](https://github.com/user-attachments/assets/96201686-6fb2-4474-ac1c-6c772e9eeece)
