### ISSUE TITLE
Existing Discord Bot configuration wiped out when installing Discord Bot on a different instance

### ISSUE THREAD

**Issue by jisnotu** [winglessraven/AMP-Discord-Bot#122]
**Describe the bug**
Existing Discord Bot configuration in AMP instance gets wiped out after running the installation script and instructing it to skip installing on the existing AMP instance (on which Discord Bot has already been set up).

**To Reproduce**
Steps to reproduce the behaviour:
_(Context: I had AMP Discord Bot already installed on 3 Minecraft instances in AMP [Minecraft01, Minecraft02, and Minecraft03]. I created a new Minecraft instance [Minecraft04] and wanted to install AMP Discord Bot on it.)_
1. Run the installation script (`python3 install_script.py`).
2. When asked, choose the default path and default ADS instance (ADS01), and provide the AMP developer key.
3. When asked whether to process Minecraft01, enter `n`. Repeat for Minecraft02 and Minecraft03.
4. When asked whether to process Minecraft04, enter `y`.
5. After the installation finishes, manage Minecraft01 in AMP. Go to Configuration > Discord Bot. The information in the "Discord Config" tab has been preserved, but all other configuration in the other tabs ("Server Info", "Buttons", "Logging", "Colours", "Game Specific", and "Misc") have been reset to the default values.
6. Interestingly, in instances Minecraft02 and Minecraft03, the Discord Bot configuration has been preserved (in all tabs).

**Expected behaviour**
The installation process should not wipe out the Discord Bot configuration for an existing AMP instance if you instruct the script to not process said AMP instance.

**Screenshots**
![Screenshot 2024-12-28 195756](https://github.com/user-attachments/assets/da1e605e-c089-44f4-a5e5-e0bc507be367)

**AMP Instance Info (please complete the following information):**
 - OS: Debian 12
 - AMP Build v2.6.0.6

**Additional context**
Below is the install script log. I'm not sure if the `SignatureVerification Error`, `Loader Error`, and `Code Error` are relevant. Despite these error messages, the Discord Bot seems to be working fine from what I can tell.
```2024-12-28 23:02:11,805 - DEBUG - Logging started at 2024-12-28 23:02:11.805342
2024-12-28 23:02:11,805 - DEBUG - WARNING: This log might contain sensitive information, like license keys, instance names and paths.
2024-12-28 23:02:11,805 - DEBUG - Do not share this log unaltered!
2024-12-28 23:02:11,805 - DEBUG - Script location: /home/amp/install_script.py
2024-12-28 23:02:53,087 - INFO - Found instances: ['ADS01', 'Minecraft01', 'Minecraft03', 'Minecraft04', 'Minecraft02']
2024-12-28 23:02:57,979 - INFO - Skipping instance Minecraft01
2024-12-28 23:03:01,089 - INFO - Skipping instance Minecraft03
2024-12-28 23:03:05,497 - INFO - Skipping instance Minecraft02
2024-12-28 23:03:05,498 - INFO - Stopping instance Minecraft04
2024-12-28 23:03:05,498 - DEBUG - Executing command: ['ampinstmgr', 'stop', 'Minecraft04']
2024-12-28 23:03:06,149 - DEBUG - [Info/1] AMP Instance Manager v2.6.0.6 built 20/11/2024 20:58
[Info/1] Stream: Mainline / Release - built by CUBECODERS/buildbot on CCL-DEV
[Info/1] Stopping Instance: 'Minecraft04'
[Info/1] Stopping instance Minecraft04...
[Info/1] Requesting soft-stop...
[Info/1] Waiting for instance to stop...
[Info/8] Instance was shut down gracefully.
[Info/8] Instance Minecraft04 has stopped.

2024-12-28 23:03:06,149 - DEBUG - 
2024-12-28 23:03:06,149 - INFO - Creating DiscordBotPlugin folder at /home/amp/.ampdata/instances/Minecraft04/Plugins/DiscordBotPlugin
2024-12-28 23:03:06,149 - INFO - Copying /home/amp/DiscordBotPlugin.dll to /home/amp/.ampdata/instances/Minecraft04/Plugins/DiscordBotPlugin
2024-12-28 23:03:06,153 - INFO - Updating AMPConfig.conf at /home/amp/.ampdata/instances/Minecraft04/AMPConfig.conf
2024-12-28 23:03:06,154 - INFO - Updated AMP.LoadPlugins in /home/amp/.ampdata/instances/Minecraft04/AMPConfig.conf
2024-12-28 23:03:06,154 - INFO - Stopping ADS01
2024-12-28 23:03:06,154 - DEBUG - Executing command: ['ampinstmgr', 'stop', 'ADS01']
2024-12-28 23:03:06,764 - DEBUG - [Info/1] AMP Instance Manager v2.6.0.6 built 20/11/2024 20:58
[Info/1] Stream: Mainline / Release - built by CUBECODERS/buildbot on CCL-DEV
[Info/1] Stopping Instance: 'ADS01'
[Info/1] Stopping instance ADS01...
[Info/1] Requesting soft-stop...
[Info/1] Waiting for instance to stop...
[Info/6] Instance was shut down gracefully.
[Info/6] Instance ADS01 has stopped.

2024-12-28 23:03:06,764 - DEBUG - 
2024-12-28 23:03:06,764 - INFO - Reactivating instance Minecraft04
2024-12-28 23:03:06,764 - DEBUG - Executing command: ['ampinstmgr', 'reactivate', 'Minecraft04', '//hidden']
2024-12-28 23:03:10,933 - DEBUG - [Info/1] AMP Instance Manager v2.6.0.6 built 20/11/2024 20:58
[Info/1] Stream: Mainline / Release - built by CUBECODERS/buildbot on CCL-DEV
[Info/1] Checking licence key...
[Info/6] Licence Type:  AMP Developer
[Info/6] Current Usage: 3
[Info/6] Reactivating instance Minecraft04...
[23:03:09] [Program Info/1]       : Starting AMP version 2.6.0.6 (Phobos), built 20/11/2024 20:57
[23:03:09] [Program Info/1]       : Stream: Mainline / Release - built by CUBECODERS/buildbot on CCL-DEV
[23:03:09] [Core Info/1]          : Loading configuration from provisionargs.kvp...
[23:03:09] [Program Info/1]       : OS: Linux / x86_64
[23:03:09] [Program Info/1]       : CPU: Intel(R) Core(TM) i3-10100 CPU @ 3.60GHz (4C/8T)
[23:03:09] [Program Info/1]       : RAM: 15878MB
[23:03:09] [Program Info/1]       : AMP Instance ID: //hidden
[23:03:09] [Core Info/1]          : Loaded MinecraftModule version 2.6.0.6 by CubeCoders Limited
[23:03:09] [Core Info/1]          : Metrics publishing is enabled at udp://localhost:12820.
[23:03:09] [Loader Info/1]        : Loaded FileManagerPlugin by CubeCoders Limited
[23:03:09] [Loader Info/1]        : Loaded EmailSenderPlugin by CubeCoders Limited
[23:03:09] [Loader Info/1]        : Loaded WebRequestPlugin by CubeCoders Limited
[23:03:09] [Loader Info/1]        : Loaded LocalFileBackupPlugin by CubeCoders Limited
[23:03:09] [Loader Info/1]        : Loaded CommonCorePlugin by CubeCoders Limited
[23:03:10] [Loader Info/1]        : Loaded AnalyticsPlugin by CubeCoders Limited
[23:03:10] [System Error/9]       : Missing plugin/assembly: MaxMind.Db (/home/amp/.ampdata/instances/Minecraft04/Plugins/DiscordBotPlugin/MaxMind.Db.dll) for DiscordBotPlugin
[23:03:10] [SignatureVerification Error/1] : ArgumentNullException
[23:03:10] [SignatureVerification Error/1] : [0] (ArgumentNullException) : Value cannot be null. (Parameter 'rawData')
[23:03:10] [SignatureVerification Error/1] :    at ArgumentNullException.Throw(String paramName)
   at Security.Cryptography.X509Certificates.X509Certificate2Collection.Import(Byte[] rawData)
   at GSMyAdmin.SignatureVerification.GetCertFromFile(String Filename)
   at GSMyAdmin.SignatureVerification.Verify_Certificate(String Filename)
[23:03:10] [Loader Error/1]       : Unable to load plugin DiscordBotPlugin: Could not load file or assembly 'DiscordBotPlugin, Culture=neutral, PublicKeyToken=null'. System.Exception (0x80131501)
   at System.Reflection.RuntimeAssembly.InternalLoad(AssemblyName assemblyName, StackCrawlMark& stackMark, AssemblyLoadContext assemblyLoadContext, RuntimeAssembly requestingAssembly, Boolean throwOnFileNotFound)
   at System.Reflection.Assembly.Load(String assemblyString)
   at GSMyAdmin.ModuleLoader.GetPluginAssembly(String PluginName)
   at GSMyAdmin.ModuleLoader.LoadPlugin(String PluginName, IApplicationWrapper app, Boolean LoadWebContent)
[23:03:10] [Core Error/1]         : Could not load plugin DiscordBotPlugin
[23:03:10] [Core Info/1]          : Performing activation, please wait...
[23:03:10] [Core Info/1]          : Activated successfully.
[23:03:10] [Core Info/1]          : Licence Present: AMP Professional Edition - Lifetime Licence
[23:03:10] [Core Info/1]          : Licence Present: AMP Developer Edition - Lifetime Licence
[23:03:10] [Program Info/1]       : -configonly specified or activation performed. Saving settings and shutting down. This is perfectly normal.
[Info/8] Done.

2024-12-28 23:03:10,933 - DEBUG - 
2024-12-28 23:03:10,933 - INFO - Starting ADS01
2024-12-28 23:03:10,933 - DEBUG - Executing command: ['ampinstmgr', 'start', 'ADS01']
2024-12-28 23:03:12,067 - DEBUG - [Info/1] AMP Instance Manager v2.6.0.6 built 20/11/2024 20:58
[Info/1] Stream: Mainline / Release - built by CUBECODERS/buildbot on CCL-DEV
[Info/1] Starting Instance: 'ADS01'
[Info/1] Waiting for AMP instance to start...
[Notice/7] AMP instance ADS01 is now running.
[Info/9] You can browse to this instance at http://127.0.1.1:8080/
[Info/9] Instance started in new session. Run 'ampinstmgr View ADS01' to view this instances live output.

2024-12-28 23:03:12,067 - DEBUG - 
2024-12-28 23:03:12,067 - INFO - Starting instance Minecraft04
2024-12-28 23:03:12,067 - DEBUG - Executing command: ['ampinstmgr', 'start', 'Minecraft04']
2024-12-28 23:03:12,695 - DEBUG - [Info/1] AMP Instance Manager v2.6.0.6 built 20/11/2024 20:58
[Info/1] Stream: Mainline / Release - built by CUBECODERS/buildbot on CCL-DEV
[Info/1] Starting Instance: 'Minecraft04'
[Info/1] Waiting for AMP instance to start...
[Notice/1] AMP instance Minecraft04 is now running.
[Info/7] You can browse to this instance at http://127.0.0.1:8084/
[Info/7] Instance started in new session. Run 'ampinstmgr View Minecraft04' to view this instances live output.

2024-12-28 23:03:12,695 - DEBUG -

**Comment by winglessraven** [comment]
Are you using the latest version of the install script?

The section that touched the plugin config file was removed back in April https://github.com/winglessraven/AMP-Discord-Bot/commit/a3fe4d1f53bbdc566d56c6c530bc3d01addf2cfe.

Current version of the script does not touch any configs, also saying no to other instances means it will not do anything to them (not even update the dll file).

**Comment by jisnotu** [comment]
Sorry about the delayed response.

I'm not sure if I'm using the latest version of the install script.

I used `wget https://raw.githubusercontent.com/winglessraven/AMP-Discord-Bot/master/install_script.py` as instructed at [https://github.com/winglessraven/AMP-Discord-Bot/wiki/How-to-Run-the-Install-Script]() to get the install script. Is that the latest version?

Right, I also thought saying no to other instances should mean that nothing will be done to them, but it ended up modifying one of the instances I said no to.

**Comment by winglessraven** [comment]
Yep, that'll be the latest one then. There is nowhere in the script that would have wiped out settings to any instance - included in your options or not.

You can see in the log that the only instances touched were `ADS01` (for dev key activation), and `Minecraft04` (to add and enable the plugin). Nowhere did it touch any other instances or config files.

It must be a bug in AMP where the settings didn't save correctly.

If something similar happens again, check the modified date/time of the file called `DiscordBotPlugin.kvp` in the root of the instance (e.g. `C:\AMPDatastore\Instances\Minecraft01\DiscordBotPlugin.kvp`) this should help narrow down when the settings were modified/lost.

**Comment by jisnotu** [comment]
Ah okay, it must have been an issue with AMP or my system. It just happened to coincide with running the install script.
I'll try checking the modified date/time if it happens again.
Sorry to bother you, and thank you for looking into this! Happy new year!

**Comment by winglessraven** [comment]
No worries, happy new year to you too!
