### ISSUE TITLE
Compatible Game List

### ISSUE THREAD

**Issue by tadavispmd040507** [winglessraven/AMP-Discord-Bot#47]
**Describe the solution you'd like**
Would like to see a list of compatible games.

**Additional context**
Doesn't seem to be compatible with Satisfactory, I expected Satisfactory since its so new. Conan Exiles seems to be partially compatible.See the image attached for Conan Exiles. 

**Member List**
![image](https://user-images.githubusercontent.com/58477652/227543206-23461c54-7821-4d30-8bf6-0241c85e5938.png)

**Running Info Command**
![image](https://user-images.githubusercontent.com/58477652/227542840-b6f46de9-a31e-41cb-9fc6-855b7dfe9389.png)

**Comment by winglessraven** [comment]
Hey,

The bot is compatible with all instances. 
Errors like the one you screenshotted suggest something isn't configured right (e.g. the bot commands permission).
First step is to check the AMP instance logs, the error might be logged there.

**Comment by tadavispmd040507** [comment]
says i need a developer license but i have one and followed the instructions...now i attached this to the game instance, does it need to be on the main instance? Error is below.

`[02:03:14] [ModuleLoader Error]   : Unable to load plugin DiscordBotPlugin: A developer licence is required to load unsigned plugins.`

**Comment by tadavispmd040507** [comment]
so I tried to reactivate it again and received the following error...

`[Error] Unable to query provisioning arguments for FileManagerPlugin
[Error] ReflectionTypeLoadException
[Error] [0] (ReflectionTypeLoadException) : Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
[Error]    at InstanceManagerPlugin.LocalInstanceManager.GetProvisionArguments(String ModuleName)
[Error] FileNotFoundException
[Error] [0] (FileNotFoundException) : Could not load file or assembly 'mHttp, Version=0.1.6296.32466, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
[Error] Unable to query provisioning arguments for FileManagerPlugin
[Error] ReflectionTypeLoadException
[Error] [0] (ReflectionTypeLoadException) : Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
[Error]    at InstanceManagerPlugin.LocalInstanceManager.GetProvisionArguments(String ModuleName)
[Error] FileNotFoundException
[Error] [0] (FileNotFoundException) : Could not load file or assembly 'mHttp, Version=0.1.6296.32466, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
[Error] Unable to query provisioning arguments for FileManagerPlugin
[Error] ReflectionTypeLoadException
[Error] [0] (ReflectionTypeLoadException) : Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
[Error]    at InstanceManagerPlugin.LocalInstanceManager.GetProvisionArguments(String ModuleName)
[Error] FileNotFoundException
[Error] [0] (FileNotFoundException) : Could not load file or assembly 'mHttp, Version=0.1.6296.32466, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
[Error] Unable to query provisioning arguments for FileManagerPlugin
[Error] ReflectionTypeLoadException
[Error] [0] (ReflectionTypeLoadException) : Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
[Error]    at InstanceManagerPlugin.LocalInstanceManager.GetProvisionArguments(String ModuleName)
[Error] FileNotFoundException
[Error] [0] (FileNotFoundException) : Could not load file or assembly 'mHttp, Version=0.1.6296.32466, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
[Error] Unable to query provisioning arguments for FileManagerPlugin
[Error] ReflectionTypeLoadException
[Error] [0] (ReflectionTypeLoadException) : Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
[Error]    at InstanceManagerPlugin.LocalInstanceManager.GetProvisionArguments(String ModuleName)
[Error] FileNotFoundException
[Error] [0] (FileNotFoundException) : Could not load file or assembly 'mHttp, Version=0.1.6296.32466, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
[Error] Unable to query provisioning arguments for FileManagerPlugin
[Error] ReflectionTypeLoadException
[Error] [0] (ReflectionTypeLoadException) : Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
[Error]    at InstanceManagerPlugin.LocalInstanceManager.GetProvisionArguments(String ModuleName)
[Error] FileNotFoundException
[Error] [0] (FileNotFoundException) : Could not load file or assembly 'mHttp, Version=0.1.6296.32466, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.`

**Comment by winglessraven** [comment]
That second error isn't related to this plugin, that's an error from the FileManagerPlugin (part of AMP). Try restarting your server if possible to see if that helps it.

Are you running in a docker container? If so you need to take it out of the container to activate a dev licence, AMP won't let you apply a dev licence when running in a container.

**Comment by tadavispmd040507** [comment]
ok i will restart and try again and no i dont run anything in containers.

**Comment by tadavispmd040507** [comment]
Restarting the server didnt do anything.

**Comment by winglessraven** [comment]
Strange. What's the command you're running? `ampinstmgr reactivate Satisfactory01 devkey`?

Also, for the Conan server, make sure the bot has the following permissions. The error you got on the command from that is likely related to that.

![image](https://user-images.githubusercontent.com/4540397/227582504-ba171284-5145-4a2c-aa56-671060a6936e.png)

**Comment by tadavispmd040507** [comment]
yes that is the command im using. I just double checked the Conan prives and i do have them set to that...I also just tried to install the bot on my Space Engineers server and got the same errors as Conan they are on the same box which is windows

**Comment by winglessraven** [comment]
To try and narrow the problem down a bit can you create a new instance (of anything) and try to activate the dev licence without changing the conf? Trying to figure out if the problem is activating it or the plugin misbehaving.

I did see that Mike was doing some maintenance on the activation server today so maybe that's part of the issue.

**Comment by tadavispmd040507** [comment]
does the ADS and all need to be on the Dev Key or just the Game Instance?

**Comment by winglessraven** [comment]
Game instances only

**Comment by tadavispmd040507** [comment]
ok let me recreate one....it might be a bit im at work

**Comment by tadavispmd040507** [comment]
ok so i was able to get it to work on Satisfactory which im running on Ubuntu, I can not get it to work on either Conan Exiles or Space Engineers which are on Windows 11 Pro, thats where all errors above came from. So is this compatiable with Windows, also those errors are only when try to Reactivate with Dev License. I have tried this on a fresh Install of Space Engineers and nothing changed.

**Comment by winglessraven** [comment]
Yep it runs fine on W11. I just created a new instance on my dev machine and it activated without any issues.

![image](https://user-images.githubusercontent.com/4540397/227758159-6e3adbec-df7a-45c0-8719-31b1653af65a.png)

Do the logs show if the licence has been applied?

![image](https://user-images.githubusercontent.com/4540397/227758456-4a35edee-2d5f-41e8-8306-6b7e5e517066.png)

**Comment by winglessraven** [comment]
Yep could very well be that. I'll keep this open until I hear back.

**Comment by tadavispmd040507** [comment]
you can close this, Ive installed a new Windows OS both pro and Server and i keep getting the same issue with the errors . I dont get these errors on Ubuntu.

**Comment by winglessraven** [comment]
Yep OK, will do. Does seem to be something to do with Windows permissions though. I've tested on W10,W11 and Server 2019 and it works fine. If you get the AMP errors sorted feel free to reach out if you need help setting this up again.
