### ISSUE TITLE
CryptographicException couldnt load Discord bot plugin

### ISSUE THREAD

**Issue by Deadsimon** [winglessraven/AMP-Discord-Bot#55]
Installed the Discord bot into a fresh non-ads instance for 7 days to die, the module refused to load despite it working in my other instance.

amp version : v2.4.5.4
OS: Windows
Docker : NO
VM : NO
Plugin version : V2.4.5

error:

[16:02:46] [Core Error]           : CryptographicException
[16:02:46] [Core Error]           : [0] (CryptographicException) : Cannot find the requested object.

[16:02:46] [Core Error]           :    at Security.Cryptography.CryptographicException.ThrowCryptographicException(Int32 hr)
   at Security.Cryptography.X509Certificates.X509Utils._QueryCertFileType(String fileName)
   at Security.Cryptography.X509Certificates.X509Certificate.LoadCertificateFromFile(String fileName, Object password, X509KeyStorageFlags keyStorageFlags)
   at GSMyAdmin.SignatureVerification.Verify_Windows(String Filename)
[16:02:46] [Loader Error]         : Unable to load plugin DiscordBotPlugin: Could not load file or assembly 'DiscordBotPlugin' or one of its dependencies. Failure during Cryptographic operation. (Exception from HRESULT: 0x80131430)
[16:02:46] [Loader Error]         : Could not load plugin DiscordBotPlugin

**Comment by winglessraven** [comment]
Hey.

Which version of AMP are you on and what OS are you using? Also, docker or no docker?

Cheers

**Comment by winglessraven** [comment]
Also, which version of the plugin are you on?

**Comment by winglessraven** [comment]
Thanks.

I've just created a new instance on Windows, same version AMP and the plugin version built for 2.4.5 (1.15.3) and it started fine (cryptographic error is usual on Windows, but it still starts).

Two things to check:

1) Make sure you have both licenses applied correctly (developer and your usual licence)
2) Re-download the .dll from [latest releases](https://github.com/winglessraven/AMP-Discord-Bot/releases/tag/1.15.3) to make sure it's not corrupted.

Is anything different between this instance and another that you have working with the plugin?

**Comment by Deadsimon** [comment]
i've done both of those things, except the first instance with the bot that is currently working doesn't have a dev key attached.

the second instance is a fresh install of seven days to die with the discord bot plugin installed according to the instructions.

full log file:
[amplog.txt](https://github.com/winglessraven/AMP-Discord-Bot/files/12164138/amplog.txt)

**Comment by winglessraven** [comment]
I just managed to replicate by trying to run the plugin without an AMP developer licence.

Try activating the instance with a dev key from CubeCoders (https://manage.cubecoders.com/).

I don't understand how your other instance is working without one to be honest!

**Comment by Deadsimon** [comment]
> I just managed to replicate by trying to run the plugin without an AMP developer licence.
> 
> Try activating the instance with a dev key from CubeCoders (https://manage.cubecoders.com/).
> 
> I don't understand how your other instance is working without one to be honest!

i have attatched the developers licence and it works now, thank you. :)
