### ISSUE TITLE
bot unable to communicate with discord

### ISSUE THREAD

**Issue by CprlRst** [winglessraven/AMP-Discord-Bot#64]
**Describe the bug**
[21:36:13] [DiscordBot:admin Info] : 22:36:13 Gateway     A SlashCommandExecuted handler has thrown an unhandled exception.:
System.NullReferenceException: Object reference not set to an instance of an object.
   at DiscordBotPlugin.PluginMain.<GetServerInfo>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at DiscordBotPlugin.PluginMain.<SlashCommandHandler>d__44.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Discord.EventExtensions.<InvokeAsync>d__1`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Discord.WebSocket.DiscordSocketClient.<TimeoutWrap>d__172.MoveNext()

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**

**Screenshots**

**AMP Instance Info (please complete the following information):**
 - OS: win11
 - AMP Build Latest

**Additional context**

**Comment by winglessraven** [comment]
When did you get that error? 

If it was when you enabled the bot, double check that you added application.commands to the permissions when you added it to your Discord server

**Comment by winglessraven** [comment]
Seems to be the same error as #66, need more info. AMPLogs and DiscordBotPlugin.kvp should help me replicate the issue.

**Comment by winglessraven** [comment]
Following on from the logs received in a similar bug report with the same error, did you try adding the bot to your ADS instance? If so it will not work, the bot needs to be added to each game server instance it is required on. Each server has a bot dedicated to it to show status individually.

![image](https://github.com/winglessraven/AMP-Discord-Bot/assets/4540397/101e3c9c-ad6f-4917-ae10-064b08900406)

**Comment by CprlRst** [comment]
ok so i need to add each to the gameserver instance and not say asd01 the main amp instance

**Comment by winglessraven** [comment]
Yep, exactly. Give it a go when you get a min - let me know if you get any more issues.

**Comment by winglessraven** [comment]
Closing issue - error was because it was being added to ADS.
