### ISSUE TITLE
Failure during Cryptographic operation

### ISSUE THREAD

**Issue by Bluscream** [winglessraven/AMP-Discord-Bot#82]
**Describe the bug**
AMP does not start with the bot installed

**To Reproduce**
Follow https://github.com/winglessraven/AMP-Discord-Bot?tab=readme-ov-file#installing-and-enabling-the-plugin

amp dev.cmd:
```batch
ampinstmgr stop ADS01
ampinstmgr reactivate ADS01 <devkey>
taskkill /f /im AMP.exe
ampinstmgr start ADS01
```

**Logs**
```
[22:47:22] [AMPService Info]      : Starting AMPService version 2.4.8.0 (Decadeus), built 29/01/2024 18:40
[22:47:22] [AMPService Info]      : Stream: Mainline / Release - built by CUBECODERS/buildbot on CCL-DEV
[22:47:22] [GSMyAdmin Info]       : Purging old audit logs (this may take a moment)...
[22:47:22] [AMPService Info]      : Running in a HyperV environment.
[22:47:23] [GSMyAdmin Warning]    : Current time zone is set to W. Europe Standard Time - It is recommended you switch to UTC+0 to avoid time-zone related issues
[22:47:23] [AMPService Info]      : OS: Windows / x86_64
[22:47:23] [AMPService Info]      : CPU: AMD EPYC Processor (with IBPB) (4C/4T)
[22:47:23] [AMPService Info]      : RAM: 8191MB
[22:47:23] [AMPService Info]      : AMP Instance ID: xxx
[22:47:23] [GSMyAdmin Warning]    : Assembly Newtonsoft.Json was loaded for Core via fallback handler, check plugin dependencies.
[22:47:23] [GSMyAdmin Info]       : Loaded ADSModule version 1.0.0.0 by CubeCoders Limited
[22:47:23] [GSMyAdmin Info]       : Loaded FileManagerPlugin by CubeCoders Limited
[22:47:23] [GSMyAdmin Info]       : Loaded EmailSenderPlugin by CubeCoders Limited
[22:47:23] [GSMyAdmin Info]       : Loaded WebRequestPlugin by CubeCoders Limited
[22:47:23] [GSMyAdmin Info]       : Loaded LocalFileBackupPlugin by CubeCoders Limited
[22:47:23] [GSMyAdmin Info]       : Loaded CommonCorePlugin by CubeCoders Limited
[22:47:23] [Core Error]           : CryptographicException
[22:47:23] [Core Error]           : [0] (CryptographicException) : Cannot find the requested object.

[22:47:23] [Core Error]           :    at Security.Cryptography.CryptographicException.ThrowCryptographicException(Int32 hr)
   at Security.Cryptography.X509Certificates.X509Utils._QueryCertFileType(String fileName)
   at Security.Cryptography.X509Certificates.X509Certificate.LoadCertificateFromFile(String fileName, Object password, X509KeyStorageFlags keyStorageFlags)
   at GSMyAdmin.SignatureVerification.Verify_Windows(String Filename)
[22:47:23] [GSMyAdmin Error]      : Unable to load plugin DiscordBotPlugin: Could not load file or assembly 'DiscordBotPlugin' or one of its dependencies. Failure during Cryptographic operation. (Exception from HRESULT: 0x80131430)
[22:47:23] [GSMyAdmin Error]      : Could not load plugin DiscordBotPlugin
[22:47:23] [GSMyAdmin Info]       : ADSModule requests dependency InstanceManagerPlugin...
```

**Comment by Bluscream** [comment]
```
[23:10:04] [AMPService Info]      : Starting AMPService version 2.4.8.0 (Decadeus), built 29/01/2024 18:40
[23:10:04] [AMPService Info]      : Stream: Mainline / Release - built by CUBECODERS/buildbot on CCL-DEV
[23:10:05] [GSMyAdmin Info]       : Purging old audit logs (this may take a moment)...
[23:10:05] [AMPService Info]      : Running in a HyperV environment.
[23:10:05] [GSMyAdmin Warning]    : Current time zone is set to W. Europe Standard Time - It is recommended you switch to UTC+0 to avoid time-zone related issues
[23:10:05] [AMPService Info]      : OS: Windows / x86_64
[23:10:05] [AMPService Info]      : CPU: AMD EPYC Processor (with IBPB) (4C/4T)
[23:10:05] [AMPService Info]      : RAM: 8191MB
[23:10:05] [AMPService Info]      : AMP Instance ID: xxxx
[23:10:06] [GSMyAdmin Warning]    : Assembly Newtonsoft.Json was loaded for Core via fallback handler, check plugin dependencies.
[23:10:06] [GSMyAdmin Info]       : Loaded ADSModule version 1.0.0.0 by CubeCoders Limited
[23:10:06] [GSMyAdmin Info]       : Loaded FileManagerPlugin by CubeCoders Limited
[23:10:07] [GSMyAdmin Info]       : Loaded EmailSenderPlugin by CubeCoders Limited
[23:10:07] [GSMyAdmin Info]       : Loaded WebRequestPlugin by CubeCoders Limited
[23:10:07] [GSMyAdmin Info]       : Loaded LocalFileBackupPlugin by CubeCoders Limited
[23:10:07] [GSMyAdmin Info]       : Loaded CommonCorePlugin by CubeCoders Limited
[23:10:07] [Core Error]           : CryptographicException
[23:10:07] [Core Error]           : [0] (CryptographicException) : Cannot find the requested object.

[23:10:07] [Core Error]           :    at Security.Cryptography.CryptographicException.ThrowCryptographicException(Int32 hr)
   at Security.Cryptography.X509Certificates.X509Utils._QueryCertFileType(String fileName)
   at Security.Cryptography.X509Certificates.X509Certificate.LoadCertificateFromFile(String fileName, Object password, X509KeyStorageFlags keyStorageFlags)
   at GSMyAdmin.SignatureVerification.Verify_Windows(String Filename)
[23:10:08] [GSMyAdmin Info]       : Loaded DiscordBotPlugin by winglessraven
[23:10:08] [GSMyAdmin Info]       : ADSModule requests dependency InstanceManagerPlugin...
[23:10:09] [GSMyAdmin Info]       : Loaded InstanceManagerPlugin by CubeCoders Limited
[23:10:09] [GSMyAdmin Info]       : ADSModule requests dependency SystemUserManagerPlugin...
[23:10:09] [GSMyAdmin Info]       : Loaded SystemUserManagerPlugin by CubeCoders Limited
[23:10:09] [GSMyAdmin Info]       : Licence Present: AMP Professional Edition
[23:10:09] [GSMyAdmin Info]       : Licence Present: AMP Developer Edition
[23:10:10] [GSMyAdmin Info]       : Loaded steamcmdplugin by CubeCoders Limited
[23:10:10] [Core Info]            : Metrics server started OK on port 12820
[23:10:10] [ADS Info]             : ADS startup complete in 437ms
[23:10:10] [ADS Info]             : Updating remote source CubeCoders/AMPTemplates
[23:10:10] [ADS Info]             : Updating existing remote source https://github.com/CubeCoders/AMPTemplates.git...
[23:10:10] [FileManager Error]    : Unable to start SFTP server.
[23:10:10] [Core Error]           : InvalidOperationException
[23:10:10] [Core Error]           : [0] (InvalidOperationException) : The specified socket is already in use.
[23:10:10] [Core Error]           :    at kdbmv.ssrok.thtoq(EndPoint p0, Boolean p1)
   at kdbmv.ssrok..ctor(EndPoint ep, String hostname, xqkcu runner)
   at Rebex.Net.Servers.Core.Server.Bind(IPEndPoint endPoint, ServerModule module)
   at FileManagerPlugin.PluginMain.PostInit()
[23:10:10] [Core Error]           : SocketException
[23:10:10] [Core Error]           : [1] (SocketException) : Only one usage of each socket address (protocol/network address/port) is normally permitted
[23:10:10] [Core Error]           :    at Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at Net.Sockets.Socket.Bind(EndPoint localEP)
   at kdbmv.ssrok.thtoq(EndPoint p0, Boolean p1)
[23:10:10] [DiscordBot Info]      : Discord Bot Activated
[23:10:10] [DiscordBot Info]      : 00:10:10 Discord     Discord.Net v1.0.0 (API v10)
[23:10:10] [DiscordBot Info]      : C:\AMPDatastore\Instances\ADS01\WebPanel-ADS01
[23:10:10] [GSMyAdmin Info]       : Websockets are enabled.
[23:10:10] [Webserver Info]       : RouterTimer@10Hz with 2 jobs started
[23:10:10] [GSMyAdmin Error]      : Socket exception - Trivial error / user error. Will not be submitted.
[23:10:10] [GSMyAdmin Info]       : Webserver started on http://0.0.0.0:8080
[23:10:10] [GSMyAdmin Error]      : [Error] --- Begin Exception Data ---
[Error] OS: Windows (x86_64/HyperV)
[Error] Module: ADSModule, Version: AMPService 2.4.8.0
[Error] Release spec: Mainline - built by CUBECODERS/buildbot on CCL-DEV
[Error] Instance ID: c36c0e53-bd14-4286-84f5-8c4597414eac
[Error] SocketException
[Error] [0] (SocketException) : Only one usage of each socket address (protocol/network address/port) is normally permitted
[Error]    at Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at Net.Sockets.Socket.Bind(EndPoint localEP)
   at Net.Sockets.TcpListener.Start(Int32 backlog)
   at m.Http.HttpBackend.ConnectionLoop()
[Error] --- End Exception Data ---
[Warning] Unsigned plugins are loaded: DiscordBotPlugin - error report will not be submitted.
[Warning] Last error was raised less than 60 minutes ago, error report will not be submitted.

[23:10:10] [GSMyAdmin Info]       : ####################################
[23:10:10] [GSMyAdmin Info]       : #         Self Diagnostics         #
[23:10:10] [GSMyAdmin Info]       : ####################################
[23:10:10] [GSMyAdmin Info]       : The IP and Port combination requested by the socket is already in use by another application. Either end the other application or re-bind this AMP instance to a different IP/port.
[23:10:11] [GSMyAdmin Info]       : Checking for AMP updates...
[23:10:11] [DiscordBot Info]      : 00:10:11 Gateway     Connecting
Already up to date.
[23:10:11] [ADS Info]             : Updating remote source Greelan/AMPTemplates:dev
[23:10:11] [ADS Info]             : Updating existing remote source https://github.com/Greelan/AMPTemplates.git...
[23:10:11] [GSMyAdmin Info]       : AMP is up to date.
```

**Comment by Bluscream** [comment]
```
[23:14:27] [DiscordBot Info]      : 00:14:27 Gateway     A SlashCommandExecuted handler has thrown an unhandled exception.:
System.NullReferenceException: Object reference not set to an instance of an object.
   at DiscordBotPlugin.PluginMain.<GetServerInfo>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at DiscordBotPlugin.PluginMain.<SlashCommandHandler>d__53.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Discord.EventExtensions.<InvokeAsync>d__1`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Discord.WebSocket.DiscordSocketClient.<TimeoutWrap>d__172.MoveNext()
```

**Comment by winglessraven** [comment]
This looks like you're trying to run it on an ADS instance. The bot needs to be added to the game server instance(s) not ads.

From the readme...
NOTE: The plugin cannot be used on ADS. It can only run on non-ADS instances.

**Comment by winglessraven** [comment]
Also, the cryptographic error happens when running on Windows. It has no bearing on the bot operations.

**Comment by Bluscream** [comment]
> This looks like you're trying to run it on an ADS instance. The bot needs to be added to the game server instance(s) not ads.
> 
> From the readme... NOTE: The plugin cannot be used on ADS. It can only run on non-ADS instances.

Ohhh,o it needs to be done for every single server? If so can i use the ssame token for all of them?

**Comment by winglessraven** [comment]
> Ohhh,o it needs to be done for every single server? If so can i use the ssame token for all of them?
Exactly, one for each game server. Tokens should be separate, that way you have a dedicated bot for each instance. e.g. 
![image](https://github.com/winglessraven/AMP-Discord-Bot/assets/4540397/57627a4e-5f90-48f2-881b-771793ca7a94)

> And can i have it set up so it automatically gets installed to new servers?
Unfortunately not, once Mike works on having a plugin store in AMP it'll be a lot easier.
