### ISSUE TITLE
Discord Bot not showing in configuration screen

### ISSUE THREAD

**Issue by darkt1981** [winglessraven/AMP-Discord-Bot#97]
**Describe the bug**
No bot control in Configuration screen after installing..

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Configuration'
2. Can't click on "Discord Bot" because its not there.

**Expected behaviour**
Menu entry being there.

**Screenshots**
none yet

**AMP Instance Info (please complete the following information):**
 - OS: Debian 12.5.0-AMD64-netinst
 - AMP Build : latest

**Additional context**
Did verything on your pahe without any errors.

**Comment by winglessraven** [comment]
Can you attach the AMP logs of the instance?

**Comment by darkt1981** [comment]
AMPLOG 2024-05-30.log

[14:52:23] [Core Info/1]          : Starting AMP version 2.5.0.10 (Callisto), built 21/05/2024 01:29
[14:52:23] [Core Info/1]          : Stream: Mainline / Release - built by CUBECODERS/buildbot on CCL-DEV
[14:52:23] [Core Info/1]          : Running in a QEMU KVM environment.
[14:52:23] [Core Warning/1]       : Current time zone is set to CET - It is recommended you switch to UTC+0 to avoid time-zone related iss>
[14:52:23] [Core Info/1]          : OS: Linux / x86_64
[14:52:23] [Core Info/1]          : CPU: Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (4C/4T)
[14:52:23] [Core Info/1]          : RAM: 28064MB
[14:52:23] [Core Info/1]          : AMP Instance ID: 6cf0131b-80d7-424d-a87c-0589217800ae
[14:52:24] [Loader Info/1]        : Loaded ADSModule version 1.0.0.0 by CubeCoders Limited
[14:52:24] [Loader Info/1]        : Loaded FileManagerPlugin by CubeCoders Limited
[14:52:24] [Loader Info/1]        : Loaded EmailSenderPlugin by CubeCoders Limited
[14:52:24] [Loader Info/1]        : Loaded WebRequestPlugin by CubeCoders Limited
[14:52:24] [Loader Info/1]        : Loaded LocalFileBackupPlugin by CubeCoders Limited
[14:52:24] [Loader Info/1]        : Loaded CommonCorePlugin by CubeCoders Limited
[14:52:24] [Loader Info/1]        : ADSModule requests dependency InstanceManagerPlugin...
[14:52:24] [Loader Info/1]        : Loaded InstanceManagerPlugin by CubeCoders Limited
[14:52:24] [Loader Info/1]        : ADSModule requests dependency SystemUserManagerPlugin...
[14:52:24] [Loader Info/1]        : Loaded SystemUserManagerPlugin by CubeCoders Limited
[14:52:24] [Core Info/1]          : Licence Present: AMP Professional Edition
[14:52:24] [Loader Info/1]        : Loaded steamcmdplugin by CubeCoders Limited
[14:52:24] [Core Info/1]          : Metrics server started OK on port 12820
[14:52:24] [ADS Info/1]           : ADS startup complete in 45ms
[14:52:24] [ADS Info/9]           : Updating remote source CubeCoders/AMPTemplates
[14:52:24] [ADS Info/9]           : Updating existing remote source https://github.com/CubeCoders/AMPTemplates.git...
[14:52:24] [FileManager Notice/1] : Using keypair with fingerprint *******************************************************
[14:52:24] [FileManager Info/1]   : SFTP Server started on 0.0.0.0:2223
[14:52:24] [Webserver Info/1]     : Websockets are enabled.
Already up to date.
[14:52:25] [Logger Info/14]       : RouterTimer@10Hz with 2 jobs started
[14:52:25] [Webserver Info/1]     : Webserver started on http://0.0.0.0:8080
[14:52:25] [Core Info/1]          : Checking for AMP updates...
[14:52:25] [Core Info/6]          : A new update is available!

**Comment by darkt1981** [comment]
not sure which logs you also need.

**Comment by winglessraven** [comment]
The log above looks like it's from your ADS. I need the logs from the instance you're trying to add the bot to.

Key parts to look for are...

`[04:48:03] [Loader Info/1]        : Loaded DiscordBotPlugin by winglessraven`
and
`[04:48:03] [Core Info/1]          : Licence Present: AMP Developer Edition`

**Comment by Kompetenzteam** [comment]
same here, installed via install_script.py, seems ok.
files are in the correct folders and DicordBotPlugin is stated as loaded in the instances status... but no DiscordBot Button for configuration is show in the instances (got 3 different)... maybe the latest update from amp crushed it? trhey changed the display to tab style....

where do i finde the instance logs then i`ll provide them
Greetz

**Comment by Kompetenzteam** [comment]
in log from the instances: 
[08:59:49] [Loader Error/1]       : Unable to load plugin DiscordBotPlugin: A developer licence is required to load unsigned plugins.
[08:59:49] [Loader Error/1]       : Could not load plugin DiscordBotPlugin

but included my Dev License as required.. no error was shown, tried several times redoing the installscript, any ideas?

**Comment by Kompetenzteam** [comment]
ANy hints why in Discord i got the Error Message: Application not responding when trying to setup the info panel in channel?

**Comment by Kompetenzteam** [comment]
Here`s the Logpart from one of my Servers:
[10:09:50] [DiscordBot:admin Info/12] : 10:09:50 Gateway     A SlashCommandExecuted handler has thrown an unhandled exception.:
Discord.Net.HttpException: The server responded with error 50013: Missing Permissions
  at Discord.Net.Queue.RequestBucket.SendAsync (Discord.Net.Queue.RestRequest request) [0x00559] in <a4614ebf4f03458b9a0091c19b082171>:0 
  at Discord.Net.Queue.RequestQueue.SendAsync (Discord.Net.Queue.RestRequest request) [0x0010e] in <a4614ebf4f03458b9a0091c19b082171>:0 
  at Discord.API.DiscordRestApiClient.SendInternalAsync (System.String method, System.String endpoint, Discord.Net.Queue.RestRequest request) [0x00157] in <a4614ebf4f03458b9a0091c19b082171>:0 
  at Discord.API.DiscordRestApiClient.SendJsonAsync[TResponse] (System.String method, System.String endpoint, System.Object payload, Discord.Net.BucketId bucketId, Discord.Net.Queue.ClientBucketType clientBucket, Discord.RequestOptions options) [0x000e9] in <a4614ebf4f03458b9a0091c19b082171>:0 
  at Discord.Rest.ChannelHelper.SendMessageAsync (Discord.IMessageChannel channel, Discord.Rest.BaseDiscordClient client, System.String text, System.Boolean isTTS, Discord.Embed embed, Discord.AllowedMentions allowedMentions, Discord.MessageReference messageReference, Discord.MessageComponent components, Discord.ISticker[] stickers, Discord.RequestOptions options, Discord.Embed[] embeds, Discord.MessageFlags flags) [0x004a2] in <a4614ebf4f03458b9a0091c19b082171>:0 
  at DiscordBotPlugin.PluginMain.GetServerInfo (System.Boolean updateExisting, Discord.WebSocket.SocketSlashCommand msg, System.Boolean Buttonless) [0x012f7] in <a4614ebf4f03458b9a0091c19b082171>:0 
  at DiscordBotPlugin.PluginMain.SlashCommandHandler (Discord.WebSocket.SocketSlashCommand command) [0x007aa] in <a4614ebf4f03458b9a0091c19b082171>:0 
  at Discord.EventExtensions.InvokeAsync[T] (Discord.AsyncEvent`1[T] eventHandler, T arg) [0x000a0] in <a4614ebf4f03458b9a0091c19b082171>:0 
  at Discord.WebSocket.DiscordSocketClient.TimeoutWrap (System.String name, System.Func`1[TResult] action) [0x001d6] in <a4614ebf4f03458b9a0091c19b082171>:0 

Which permission am i missing for the bot?

**Comment by Kompetenzteam** [comment]
OK got it working, had to add the user to the channel and grant the same rights as for the bot (send message, embed link, manage message, see message history)

**Comment by AshleyVargrand** [comment]
Have allways this one: 

`13:06:36 Gateway A SlashCommandExecuted handler has thrown an unhandled exception.: System.NullReferenceException: Object reference not set to an instance of an object. at DiscordBotPlugin.PluginMain.<GetServerInfo>d__27.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Runtime.CompilerServices.TaskAwaiter.GetResult() at DiscordBotPlugin.PluginMain.<SlashCommandHandler>d__57.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult() at Discord.EventExtensions.<InvokeAsync>d__1`1.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult() at Discord.WebSocket.DiscordSocketClient.<TimeoutWrap>d__179.MoveNext()`

**Comment by winglessraven** [comment]
> Have allways this one:
> 
> `13:06:36 Gateway A SlashCommandExecuted handler has thrown an unhandled exception.: System.NullReferenceException: Object reference not set to an instance of an object. at DiscordBotPlugin.PluginMain.<GetServerInfo>d__27.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Runtime.CompilerServices.TaskAwaiter.GetResult() at DiscordBotPlugin.PluginMain.<SlashCommandHandler>d__57.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult() at Discord.EventExtensions.<InvokeAsync>d__1`1.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult() at Discord.WebSocket.DiscordSocketClient.d__179.MoveNext()`

I've seen that error before when the bot was added to ADS instead of a server instance. What instance have you added it to?

**Comment by AshleyVargrand** [comment]
ah yes sorry, have installed in the ADS Instance. 

But have another Question about the "Discord Role Name" Setting. How its possible to take 2 Roles? separated with a comma?

**Comment by winglessraven** [comment]
> ah yes sorry, have installed in the ADS Instance.
> 
> But have another Question about the "Discord Role Name" Setting. How its possible to take 2 Roles? separated with a comma?

It only takes one role at the moment. I'll build in the facility to have multiple in the next update.

**Comment by winglessraven** [comment]
> ah yes sorry, have installed in the ADS Instance.
> 
> But have another Question about the "Discord Role Name" Setting. How its possible to take 2 Roles? separated with a comma?

Option now added in latest release - https://github.com/winglessraven/AMP-Discord-Bot/releases/tag/1.21.1

Separate the required roles with a comma

**Comment by darkt1981** [comment]
think i found the issue:
[15:25:00] [Loader Error/1]       : Unable to load plugin DiscordBotPlugin: Could not load file or assembly 'DiscordBotPlugin' or one of its dependencies. Failure during Cryptographic operation. (Exception from HRESULT: 0x80131430)
[15:25:00] [Loader Error/1]       : Could not load plugin DiscordBotPlugin

But the dll is installed in:
F:\AMPDatastore\Instances\Soulmask101\Plugins\DiscordBotPlugin\DiscordBotPlugin.dll

yet it fails to load for some reason.

**Comment by winglessraven** [comment]
Can you upload the full logs for the `Soulmask101` instance? I need the full context around the errors.

**Comment by winglessraven** [comment]
Also, if you're running on Windows, the Cryptographic error is normal and does not stop the bot running. E.g...

```
[06:27:48] [Program Info/1]       : Starting AMP version 2.5.0.14 (Callisto), built 07/06/2024 22:54
[06:27:48] [Program Info/1]       : Stream: Development / Development - built by CUBECODERS/buildbot on CCL-DEV
[06:27:48] [Core Debug/1]         : Loading locale data for xx from xx.json...
[06:27:48] [Program Info/1]       : OS: Windows / x86_64
[06:27:48] [Program Info/1]       : CPU: Intel(R) Core(TM) i7-10700F CPU @ 2.90GHz (8C/16T)
[06:27:48] [Program Info/1]       : RAM: 32679MB
[06:27:48] [Program Info/1]       : AMP Instance ID: 5b19e55f-aef2-4a78-bc95-8fd56810689d
[06:27:48] [Program Debug/1]      : Configuring licencing, crypto and webserver...
[06:27:48] [Licencing Debug/1]    : Primary network interface ID is {4374DFAB-32BF-4209-AEA8-F62C33048FF0} with physical address 244BFEDFB7C5
[06:27:48] [Licencing Debug/1]    : Primary network interface ID is {4374DFAB-32BF-4209-AEA8-F62C33048FF0} with physical address 244BFEDFB7C5
[06:27:48] [Config Debug/1]       : Setting up secure value store with machine hash: ezQzNzRERkFCLTMyQkYtNDIwOS1BRUE4LUY2MkMzMzA0OEZGMH0yNDRCRkVERkI3QzU=
[06:27:48] [Program Debug/1]      : Configuring shared components...
[06:27:48] [Core Debug/1]         : Using remote login server http://localhost:8080/
[06:27:48] [Program Debug/1]      : Configuring application module...
[06:27:48] [Minecraft Debug/1]    : Checking for installed plugins and retrieving metadata. (async)
[06:27:48] [Loader Info/1]        : Loaded MinecraftModule version 1.0.0.3 by CubeCoders Limited
[06:27:48] [Program Debug/1]      : Configuring scheduler...
[06:27:48] [Core Info/1]          : Metrics publishing is enabled at udp://localhost:12820.
[06:27:48] [Loader Info/1]        : Loaded FileManagerPlugin by CubeCoders Limited
[06:27:48] [Loader Info/1]        : Loaded EmailSenderPlugin by CubeCoders Limited
[06:27:48] [Loader Info/1]        : Loaded WebRequestPlugin by CubeCoders Limited
[06:27:48] [FileBackup Debug/1]   : Read manifests for 4 backups.
[06:27:48] [Loader Info/1]        : Loaded LocalFileBackupPlugin by CubeCoders Limited
[06:27:48] [Loader Info/1]        : Loaded CommonCorePlugin by CubeCoders Limited
[06:27:48] [Core Error/1]         : CryptographicException
[06:27:48] [Core Error/1]         : [0] (CryptographicException) : Cannot find the requested object.

[06:27:48] [Core Error/1]         :    at Security.Cryptography.CryptographicException.ThrowCryptographicException(Int32 hr)
   at Security.Cryptography.X509Certificates.X509Utils._QueryCertFileType(String fileName)
   at Security.Cryptography.X509Certificates.X509Certificate.LoadCertificateFromFile(String fileName, Object password, X509KeyStorageFlags keyStorageFlags)
   at GSMyAdmin.SignatureVerification.Verify_Windows(String Filename)
[06:27:49] [Loader Info/1]        : Loaded DiscordBotPlugin by winglessraven
[06:27:49] [Program Debug/1]      : Checking settings...
[06:27:49] [Core Info/1]          : Licence Present: AMP Patreon Supporter Edition
[06:27:49] [Core Info/1]          : Licence Present: AMP Developer Edition
```

**Comment by darkt1981** [comment]
[AMPLOG 2024-06-12 15-48-02.log](https://github.com/user-attachments/files/15809191/AMPLOG.2024-06-12.15-48-02.log)

there you go

**Comment by winglessraven** [comment]
First issue I can see is that you don't have a developer licence added to this instance (run `ampinstmgr reactivate Soulmask101 [DevKey]`. 

Add that and try again - if it still fails, send the log after you've added it.

**Comment by darkt1981** [comment]
issue fixed thank you
